### ISSUE TITLE
Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by cccccccccccccccccnrd** [zamu87/epd4in2#1]
Hi, unfortunately I get this error while `npm install epd4in2`, maybe it has something to do with your `binding.gyp` file? 

```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/pi/.nvm/versions/node/v11.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v11.14.0/bin/node" "/home/pi/.nvm/versions/node/v11.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/node-gd
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN pi@1.0.0 No description
npm WARN pi@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gd@1.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by cccccccccccccccccnrd** [comment]
Got it to work now. Had to run `sudo apt-get install libgd2-dev` before.

**Comment by 1ucki** [comment]
I found the error not @cccccccccccccccccnrd !
